apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: release-promotion-sample
  description: CICD tribe release-promotion-sample app
  annotations:
    sonarqube.org/project-key: release-promotion-sample-preview
    argocd/app-selector: ProductComponents=release-promotion-sample
    gitlab.com/project-id: "729"
  tags:
    - test
    - my
spec:
  type: service
  lifecycle: production
  owner: user:guest
  system: github-test